"""incremented outgoing_sms text size

Revision ID: 921e32737830
Revises: 9625ad71057a
Create Date: 2018-09-30 23:46:31.474795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '921e32737830'
down_revision = '9625ad71057a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outgoing_sms', 'text',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outgoing_sms', 'text',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=True)
    # ### end Alembic commands ###
