"""added created_at to remaining models

Revision ID: 9625ad71057a
Revises: 314d6c8a5075
Create Date: 2018-09-29 11:23:05.811752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9625ad71057a'
down_revision = '314d6c8a5075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('incoming_calls', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('outgoing_sms', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('question_options', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'created_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('question_options', 'created_at')
    op.drop_column('outgoing_sms', 'created_at')
    op.drop_column('incoming_calls', 'created_at')
    op.drop_column('attempts', 'created_at')
    # ### end Alembic commands ###
